### ISSUE TITLE
Colorbar shows wrong values when using `Contourf`, with `colorrange` or `levels`

### ISSUE THREAD

**Issue by laikq** [MakieOrg/AlgebraOfGraphics.jl#490]
## Bug description

Using `visual(Contourf; colorrange=(x, y))` will result in an incorrect plot where the colorbar does not reflect the values being plotted. This is apparently because setting `colorrange` does not actually affect the `Contourf` plot, and just sets the colorbar boundaries. Setting `levels` instead of `colorrange` will give the expected colors, but does not affect the colorbar.

**Workaround:** Use `visual(Contourf; colorrange=(x, y), levels=range(x, y))` simultaneously.

## Steps to reproduce

Setup code:
```julia
x = range(-2π, 2π, 30)
dat = [(x, y, sin(x+y)) for (x, y) in Iterators.product(x, x)] |> vec
df = DataFrame(dat, [:x, :y, :val])
```

Correct behavior using `visual(Heatmap; colorrange)` for comparison:
```julia
data(df) * mapping(:x, :y, :val) * visual(Heatmap; colormap=:curl, colorrange=(-1, 3)) |> draw
```
![](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/55911173/2a9b30f5-4aea-4c66-a49d-ac9b06a732ef)
_Using Heatmap, the crests of the sine are correctly displayed in white. The colorbar correctly identifies white as the value 1_

Incorrect behavior using `visual(Contourf; colorrange)`:
```julia
data(df) * mapping(:x, :y, :val) * visual(Contourf; colormap=:curl, colorrange=(-1, 3)) |> draw
```
![](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/55911173/272bf057-02b3-4c91-ad3f-f8f621e3ad95)
_Using Contourf with colorrange, the crests of the sine are displayed as dark red, which would correspond to a value of 3 according to the colorbar. This is incorrect_

(A bit less, but still) incorrect behavior using `visual(Contourf; levels)`:
```julia
data(df) * mapping(:x, :y, :val) * visual(Contourf; colormap=:curl, levels=-1:0.4:3) |> draw
```
![](https://github.com/MakieOrg/AlgebraOfGraphics.jl/assets/55911173/1f50f2e0-12d5-4b3c-809a-62a6ed68242b)
_Using Contourf with levels, the crests of the sine are now correctly displayed as white. However, the colorbar incorrectly identifies white with the value 0_

## Version info

- Julia Version: 1.9.3 (commit bed2cd540a)
- AlgebraOfGraphics Version: 0.6.18
- CairoMakie Version: 0.11.9

_(edit: Tested with the newest AlgebraOfGraphics & CairoMakie — Apologies for not doing that from the start!)_

**Comment by jkrumbiegel** [comment]
Since AoG 0.7 there is a `filled_contours` analysis for this case. It was not possible to link the `contourf` recipe into the new system because of the custom way it determines the actual categorical color bands it is going to use (which makes a continuous colorbar inappropriate in any case).

Using this with your example, you now get a categorical legend marking each band separately (like ggplot does it).

```julia
x = range(-2π, 2π, 30)
dat = [(x, y, sin(x+y)) for (x, y) in Iterators.product(x, x)] |> vec
df = DataFrame(dat, [:x, :y, :val])

with_theme(colormap = :curl) do
    data(df) * mapping(:x, :y, :val) * filled_contours(levels=-1:0.4:3) |> draw
end
```

<img width="519" alt="image" src="https://github.com/user-attachments/assets/1ff149c4-fe6f-4a85-88ef-7864b9d1aea1">

(Note that I use `with_theme` here out of laziness, because `curl` is not a categorical colormap, so currently, to pass it as a `palette` to the `Color` scale, I'd have to count the levels manually first and make a categorical palette with `cgrad` for example)
