### ISSUE TITLE
Linestyle in 0.7 legend is less readable

### ISSUE THREAD

**Issue by nathanrboyer** [MakieOrg/AlgebraOfGraphics.jl#512]
## Bug description

In version 0.6, the `linestyle` was legible in the legend regardless of the `linewidth`.
![download](https://github.com/user-attachments/assets/7a1d8cc6-9d76-43cd-bcb2-6c12aa5e0fcc)

In version 0.7, it is harder to tell what `linestyle` the legend is trying to represent. The gap in the line looks either like a smudge or like it is representing a dash-dot type line.
![download](https://github.com/user-attachments/assets/ac943f81-f03e-4f52-9e07-3e87837eae97)

## Steps to reproduce

MWE:
```julia
using DataFrames, AlgebraOfGraphics, CairoMakie
df1 = DataFrame(
    x = 1:5,
    y = 1:5,
    label = "Label 1",
)
df2 = DataFrame(
    x = 1:5,
    y = 5:-1:1,
    label = "Label 2",
)
plot = visual(Lines, linewidth=3) *
       mapping(:x, :y, linestyle=:label=>"Data Label") *
       (data(df1) + data(df2))
draw(plot)
```

## Version info

```
julia> versioninfo()
Julia Version 1.11.0-rc1
Commit 3a35aec36d (2024-06-25 10:23 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_EDITOR = code.cmd
  JULIA_NUM_THREADS =
```

```
⌅ [cbdf2221] AlgebraOfGraphics v0.6.20
  [13f3f980] CairoMakie v0.12.5
  [a93c6f00] DataFrames v1.6.1
```

**Comment by jkrumbiegel** [comment]
One man's fix is another man's issue :)

This is because in 0.7, all the other plot attributes that are not mapped are also considered for the legend (which is generally desired), in your case it's thicker linewidth and that's what makes the legend less readable at default settings. You can either reduce the linewidth of the plot or increase the [legend's patch size](https://docs.makie.org/stable/reference/blocks/legend#patchsize). Currently, one cannot individually modify legend entries, but you couldn't do that before, either.

I'm going to close this as it's neither a bug, nor is it planned to change the behavior.

**Comment by nathanrboyer** [comment]
`patchsize` is a good fix. Thanks.
