### ISSUE TITLE
How to deal with plotting functions where positional args are not necessarily x and y

### ISSUE THREAD

**Issue by jkrumbiegel** [MakieOrg/AlgebraOfGraphics.jl#97]
For example, all the flipped versions of plotting functions, like a vertical density, or a horizontal boxplot. I guess AlgebraOfGraphics would not necessarily complain about such a function, but the axis labels would be wrong if the assumption is that the first argument is always `x` and the second always `y`. How can this be made generic?

**Comment by piever** [comment]
I think somehow there should be a trait on recipes that tells you the orientation. Alternatively, this could be done upstream, and AbstractPlotting could support working with named arrays (AoG uses [NamedDims](https://github.com/invenia/NamedDims.jl)) and take care of the automatic axis labeling. It's already a concrete problem, for example in `QQNorm` one already gets the label on the wrong axis.

**Comment by haberdashPI** [comment]
Just ran into a case where I'd like to be able to do this. I'm interested helping to move this forward.

> I think somehow there should be a trait on recipes that tells you the orientation

Can you elaborate on this point a bit? As I understand it, this is already true. E.g. one can simply check that `:orentation in propertynames(plot) && plot.orentation == :horizontal`, since this is the keyword all existing Makie recipes use to indicate a flipped axis.

**Comment by jkrumbiegel** [comment]
I'm pretty sure not all but that's something we wanted to clean up as well

**Comment by haberdashPI** [comment]
Ah, got it. Well, a simple fix for the time being would  simply be to define the check I proposed in a method and allow the exceptions to define a specialized method. Right?
